### ISSUE TITLE
默认django2.1.1是否太新？都不支持mysql5.5.

### ISSUE THREAD

**Issue by signifox** [geeeeeeeek/videoproject#1]
https://docs.djangoproject.com/en/2.1/releases/2.1/#dropped-support-for-mysql-5-5

**Comment by signifox** [comment]
教程还缺两步：

1. 为每个app构建db表
    python manage.py makemigrations  app

2. 初始化数据库
    python manage.py migrate

**Comment by geeeeeeeek** [comment]
目前支持django 3.2版本
