### ISSUE TITLE
订阅邮件模板mail_template.html的图片路径应修改

### ISSUE THREAD

**Issue by sadjjk** [geeeeeeeek/videoproject#3]
![image](https://user-images.githubusercontent.com/27802765/55136080-64bbf900-5168-11e9-8ef2-5bdd4a5c3b59.png)
这地方的路径不合适 导致收到的邮件中图片无法显示
修改为{{site_url}}/upload/{{video.cover}}  可正常显示

**Comment by geeeeeeeek** [comment]
> ![image](https://user-images.githubusercontent.com/27802765/55136080-64bbf900-5168-11e9-8ef2-5bdd4a5c3b59.png)
> 这地方的路径不合适 导致收到的邮件中图片无法显示
> 修改为{{site_url}}/upload/{{video.cover}} 可正常显示

是的。改为自己的链接即可。
