### ISSUE TITLE
执行 ython manage.py migrate报错

### ISSUE THREAD

**Issue by lizhiyou88** [geeeeeeeek/videoproject#32]
执行
python manage.py migrate

报错

django.db.utils.OperationalError: (1824, "Failed to open the referenced table 'v_user'")
python为3.8
什么原因

**Comment by hallantern** [comment]
应该是本地的数据库没建，我也在找建数据表的sql代码

**Comment by FelexTriz** [comment]
> 应该是本地的数据库没建，我也在找建数据表的sql代码

你找到了吗

**Comment by 2144533854** [comment]
已解决。https://github.com/geeeeeeeek/videoproject/issues/34#issue-1806843891
