### ISSUE TITLE
myadmin/chunked_upload bad request怎么解决啊，上传不了视频

### ISSUE THREAD

**Issue by zzzLAsuka** [geeeeeeeek/videoproject#35]

**Comment by wpf1111** [comment]
> _No description provided._

![YIQEX7TFRWZ7E$~B@AC79TX](https://github.com/geeeeeeeek/videoproject/assets/120255573/9feb7c9a-53ed-4cd1-9a49-9953d79269f6)
我在后台登录就进不去了，填注册的那个账号进不去
