### ISSUE TITLE
需要这样一些功能，是否允许注册可选，单视频设置是否密码访问，可选择统计目标用户的浏览记录 ……

### ISSUE THREAD

**Issue by tingyue-wu** [geeeeeeeek/videoproject#36]
需要这样一些功能，注册开放关闭可选，单视频设置是否密码访问，可选择统计目标用户（用户分组）的浏览历史和每个视频观看时间
这些功能主要方便查看和统计学生是否观看了课程学习视频和各班观看比例
视频文件的类型也支持多一些，ts、mkv、mp4、mov、avi、flv
视频支持粘贴外链，不一定要上传本地

**Comment by geeeeeeeek** [comment]
外链，恩。可以
