### ISSUE TITLE
没有数据库sql

### ISSUE THREAD

**Issue by Gerflet** [geeeeeeeek/videoproject#6]

**Comment by geeeeeeeek** [comment]
README.md里面有数据库的下载链接

**Comment by fa-fa-fa** [comment]
> README.md里面有数据库的下载链接

前辈，下载完了怎么用啊

**Comment by fa-fa-fa** [comment]
> README.md里面有数据库的下载链接

老哥，你知道下载完了怎么用那个数据库文件吗？我用的u版图系统

**Comment by geeeeeeeek** [comment]
数据库迁移命令：
python manage.py makemigrations
python manage.py migrate

**Comment by hallantern** [comment]
> README.md里面有数据库的下载链接

2023年四月过来的，我好像没有在README.md里面找到sql代码

**Comment by FelexTriz** [comment]
> > README.md里面有数据库的下载链接
> 
> 2023年四月过来的，我好像没有在README.md里面找到sql代码

同

**Comment by FelexTriz** [comment]
> python manage.py makemigrations

作者您好，我迁移失败了
django.db.utils.OperationalError: (1824, "Failed to open the referenced table 'v_user'")

**Comment by GaiFauu** [comment]
什么？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月26日(周三) 中午11:41
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [geeeeeeeek/videoproject] 没有数据库sql (#6)




   
README.md里面有数据库的下载链接
  
2023年四月过来的，我好像没有在README.md里面找到sql代码
  
同

**Comment by yuanmouren1hao** [comment]
没有sql的来这里看一看，
https://github.com/yuanmouren1hao/videoproject/blob/master/some.sql

**Comment by 2144533854** [comment]
已解决。https://github.com/geeeeeeeek/videoproject/issues/34#issue-1806843891
