### ISSUE TITLE
2019-11-16：视频加载极度缓慢，视频播放严重卡顿，已无法播放

### ISSUE THREAD

**Issue by MiriaPan** [geeeeeeeek/videoproject#9]

**Comment by geeeeeeeek** [comment]
服务器流量有限。

**Comment by NothingLZ** [comment]
可以做出配置url和上传视频两种，url可以加速

**Comment by NothingLZ** [comment]
![image](https://user-images.githubusercontent.com/12367891/75684568-fd8db980-5cd3-11ea-8737-5c0b2a71ddae.png)
上传视频，前端播放的时候报错
